version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "mambaforge-latest"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/source/conf.py

conda:
  environment: .rtd-environment.yml

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements.txt
   - method: setuptools
